#!/bin/sh
set -e

case "$1" in
    configure)
        # Ensure dports binary is executable
        chmod 755 /usr/bin/dports
        ;;
    abort-upgrade|abort-remove|abort-deconfigure)
        ;;
    *)
        echo "postinst called with unknown argument '$1'" >&2
        exit 1
        ;;
esac

exit 0
